### PR TITLE
SMT-LIB solver integration

### PR DESCRIPTION
**Pull request by as3810t**
This pull request adds a new solver implementation next to the already existing Z3 solver. This new implementation uses the [SMT-LIB](http://smtlib.cs.uiowa.edu/) standard to communicate with the SMT solvers, so the underlying solver becomes changeable as long as it supports SMT-LIB.

This is an alpha feature, with known shortcomings. These shortcomings will need to be addressed in the future (see #71).

### The main features of this pull request:

- SMT-LIB solver integration
  - Support for booleans, integers, rationals, arrays, bitvectors, floating-points, quantifiers and unary uninterpreted functions
  - Support for unsat cores
  - Interpolation support (where applicable)
    - Binary, sequence, tree interpolation
- CLI tool of solver installer scripts for easy solver management, with support for
  - Boolector
  - CVC4
  - MathSAT
  - Princess
  - SMTInterpol
  - Yices2
  - Z3
- Integration with the CFA-CLI tool
  - Allows specifying different solvers for abstraction and refinement phase

### CODE REVIEW

**Comment by as3810t** [comment]
@hajduakos What is your take on the testing part of the TODO list?

**Comment by hajduakos** [comment]
First of all, this is a really impressive job!

I will think a bit about the tests. Maybe we can also ask some advice from @micskeiz . However, why are there 1000+ commits? Some of them seem irrelevant to this branch (they are already part of master)? What happened here?

**Comment by as3810t** [comment]
Yes, unfortunately the commit history is a bit tainted. The main reason / problem is the changes introduced in #101, I think. After merging the master branch, git failed to do a merge, even after resolving the conflicts. After resolving the conflicts, git merge failed, and left staged changes on files that were deleted on both the master and on this branch. These files were files that I deleted and the master moved somewhere.

**Comment by hajduakos** [comment]
Cool! Maybe @kris7t or @szdan97 can help cleaning up commits as well.

**Comment by as3810t** [comment]
The final version introduces changes in the overall project structure and also changes in the core API related to solvers.

The project structure changes by moving solver related subprojects from `common` to `solver`. Moreover it introduces a new solver `solver-smtlib` that is based on SMT-LIB, and a new CLI tool to manage it.

The changes in API are the refactoring of `Solver` and `ItpSolver` interfaces. Right now, `Solver` only contains methods for simple satisfiability checks, `UCSolver` for unsatisfiable core enabled solvers and `ItpSolver` for interpolation based solvers.

**Comment by as3810t** [comment]
@hajduakos This version introduces major changes in alpha version. Which would you prefer: to bump only the minor version (`2.24.0`) or the major as well (`3.0.0`).

**Comment by as3810t** [comment]
Close in favor of #143 , which clears the commit history of this PR.

**Pull request closed without merging**
